# Generated by Django 6.0.2 on 2026-02-17 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_faculty_teachers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('credit', models.SmallIntegerField(max_length=150)),
                ('resources', models.SmallIntegerField(max_length=10)),
                ('tasks_number', models.SmallIntegerField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='teachers',
            name='phone_number',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
