# Generated by Django 6.0.2 on 2026-02-18 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_subjects_teachers_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('condition', models.SmallIntegerField()),
                ('course', models.SmallIntegerField()),
                ('major', models.CharField(max_length=150)),
            ],
        ),
    ]
