# Generated by Django 6.0.2 on 2026-02-18 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_finance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance',
            name='condition',
            field=models.CharField(max_length=50),
        ),
    ]
