# Generated by Django 6.0.2 on 2026-02-18 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_finance_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='finance',
            name='students',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.students'),
        ),
    ]
