# Generated by Django 6.0.2 on 2026-02-19 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_finance_students'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Faculty',
        ),
        migrations.RemoveField(
            model_name='finance',
            name='students',
        ),
        migrations.DeleteModel(
            name='Subjects',
        ),
        migrations.DeleteModel(
            name='Teachers',
        ),
        migrations.DeleteModel(
            name='Finance',
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
